spring:
  application:
    name: stock-brain

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_brain
    username: postgres
    password: "102030"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

stock-brain:
  alpha-vantage:
    api-key: 2L3YEGX6OAUEF3Z1
  brapi:
    token: "aJXWrkCLz4tdYQNsYtfjGh"